#!/bin/sh

ROOTDIR=$(realpath $(dirname $0)/../)

tty --quiet

if [ $? -eq 0 ]; then
    TTY="-ti"
fi;

exec docker run --rm ${TTY} \
    -v ${ROOTDIR}:${ROOTDIR} \
    -w ${ROOTDIR} \
    ruby:2-alpine $@
